title: "Proprietary Fingerprint Template Evaluation (PFT)"
description: "Supplemental information regarding NIST's Proprietary Fingerprint Template Evaluation"
baseurl: "/pft"
rooturl: "https://pages.nist.gov"
